// components/my-mslot/my-mslot.js
Component({//component构造器
  properties:{
    //让使用者传入数据
  title:{
    type:String,
    value:''
  }
  },
  data:{
    //初始化数据
    counter:0
  },
  methods:{
    //定义内部方法
  },
  options:({
    //配置选项
    //允许多插槽
    multipleSlots:true,
    //样式隔离
    styleIsolation:true
  }),
  //传入额外样式
  externalClasses:[],
  observers:{
    //监听data，没有oldVal
    counter:function(newVal){
    }
    //监听properties，也没有oldVal
  },
  //监听生命周期
  //a.监听使用组件的页面
  pageLifetimes:{
    show(){
      console.log('监听组件所在页面显示出来时')
    },
    hide(){
      console.log('监听组件所在页面隐藏起来时')
    },
    resize(){
      console.log('监听组件所在页面尺寸改变')
    }
  },
  //b.监听当前组件
  /*
  lifetimes:{
    created(){
      console.log('组件被创建')
    },
    attached(){
      console.log('组件被添加')
    },
    ready(){
      console.log('组件被渲染')
    },
    moved(){
      console.log('组件被移到另一个节点')
    },
    detached(){
      console.log('组件被移除')
    }

  }*/
})
